### ISSUE TITLE
Envoie d'un email de confirmation à la création d'un compte

### ISSUE THREAD

**Issue by beauraF** [DoEat/api.doeat#10]
Lors de la création d'un compte DoEat, il faudrait envoyé un email de confirmation.
Il faut donc gérer les comptes confirmé / non confirmé.

**Comment by AntoineDewaele** [comment]
C'est prévu pour le prochain suivi

**Comment by gaetanm** [comment]
@AntoineDewaele Tu penses utiliser le module `confirmable` de Devise ou faire un truc à la main ?

**Comment by gaetanm** [comment]
Après, le faire à la main c'est pas très dur/long. 

Je pensais au module de Devise car j'ai vu qu'il était dans le `Gemfile`. D'ailleurs, ont l'utilise à quel niveau dans l'app actuellement ? Pour quel besoin ?

**Comment by AntoineDewaele** [comment]
Le module confirmable de Devise est utilie pour une app (car il permet des redirects plus simple, un enregistrement en base...).
Dans le cas d'une API, ce sont els clients qui gérent les redirects. Je pense faire ca à la main, il n'y a rien de sorcier.

**Comment by AntoineDewaele** [comment]
6251736bdbe4886cc8edec924eff0050982a085e
