### ISSUE TITLE
Gérer la connexion via OAuth

### ISSUE THREAD

**Issue by gaetanm** [DoEat/api.doeat#11]
Actuellement, l'API ne gère pas la connexion via provider (OAuth).

Ce que tu peux faire, c’est créer une route qui renvoie vers une méthode, par exemple`sessions#create_auth`, et qui prend en data JSON le nom du provider (ex: "twitter") + le token renvoyé par le provider + l’uid + les infos sup relatives au compte que l’on a besoin (email, nom et prénom). 

Dans cette méthode, tu check si c'est la première co de l'user ou non. Si oui, tu crées un compte. Un truc du genre (à mettre au niveau du modèle User) :
```ruby
def self.from_omniauth(auth)
  user = where(provider: auth['provider'], uid: auth['uid']).first_or_create do |user|
  user.provider = auth['provider']
  user.uid  = auth['uid']
  user.email = auth['info']['email']
  user.first_name = auth['info']['first_name']
  user.last_name = auth['info']['last_name']
  user.password = Devise.friendly_token[0,20]
end
```

Ensuite tu fais comme dans `sessions#create`.

Après niveau sécu c'est pas top, n'importe qui peut appeler cette route. Ce qu'on peut faire, étant donné qu'on sait que seulement NOS apps vont utiliser cette route (client web et mobile) on peut ajouter dans le JSON une data comme `device_token`. Ce token sera généré au préalable à la main et sera présent dans le modèle `ApiConsumer`. Perso, j'avais déjà anticipé ça dans `Authenticator` :

```ruby
def authenticate_token
  authenticate_with_http_token do |token, _|
    User.find_by_api_token(token) || ApiConsumer.find_by_api_token(token)
  end
end
```

**Comment by AntoineDewaele** [comment]
Je pense que le token est mieux à passer dans le header de la requête (comme le token d'authentification des utilisateurs) non ?

**Comment by gaetanm** [comment]
Oui. Erreur de ma part. :)

**Comment by gaetanm** [comment]
J'imagine que c'est pas encore mis en place ?

**Comment by AntoineDewaele** [comment]
Non je n'ai pas eu le temps. Mais c'est ma première tache pour le prochain suivi.

**Comment by AntoineDewaele** [comment]
Dans le cas ou un utilisateur veux se connecter une fois avec son compte Twitter et le lendemain avec son compte Facebook, ce n'est pas mieux de créer une table ```Provider``` ou on y mettre l'uid, le token et le nom et qu'on liera en ```belongs_to``` au user ?

**Comment by gaetanm** [comment]
Oui !
