### ISSUE TITLE
Sign in : user not exist

### ISSUE THREAD

**Issue by beauraF** [DoEat/api.doeat#15]
Implémenter un retour API sur le sign_in lorsque l'adresse email entré n'existe pas.

**Comment by gaetanm** [comment]
C'est pas déjà implémenté ? 🤔

Il se passe quoi actuellement si tu entres une adresse email qui n'existe pas ?

**Comment by beauraF** [comment]
Peut-être. A vrai dire je n'ai pas essayer. Sûrement la doc qui n'est pas à jour. :)

**Comment by AntoineDewaele** [comment]
Le retour est le même que pour le mot de passe (#14) ! 422 "Invalid email or password" ! 
Je peux faire un message différent selon si c'est le user ou le mot de passe qui est incorrect mais je ne vois pas trop l'intêret.

**Comment by beauraF** [comment]
C'est parfait. Pour ce cas, je préfère ne pas faire la distinction. Je trouve ça plus "secure". Je close.
