### ISSUE TITLE
Création d'un compte : erreurs

### ISSUE THREAD

**Issue by beauraF** [DoEat/api.doeat#16]
A gérer :

- [x] Addresse mail mal formatté
- [x] Date de naissance pas dans notre fourchette
- [x] Mot de passe qui ne respecte pas notre politique de mot de passe

**Comment by AntoineDewaele** [comment]
Doc mis à jour

**Comment by beauraF** [comment]
Pour la date de naissance, ce n'est pas uniquement les dates dans le futur, mais également les dates ne rentrant pas dans l'age légal fixé.
