### ISSUE TITLE
Acceptation ID null

### ISSUE THREAD

**Issue by Miyabimaru** [DoEat/api.doeat#17]
Pour la création (de User ou Recipe par exemple), la librairie que j'utilise pour créer les documents Json me le crée comme ceci avec un `id` égal à `null` :
```
{
  "data": {
    "type": "users",
    "id": null,
    "attributes": {
      "first-name": "test",
      "last-name": "test",
      "email": "test@test.fr",
      "password": "doeat_pass",
      "password-confirmation": "doeat_pass"
    }
  }
}
```
Cela fonctionnait jusqu'alors et suite aux dernière modifications de l'API celle-ci n'accepte plus l'attribut `id` sur les requêtes de création.
J'ai cherché et n'ai pas trouvé de solution pour remove cet `id` dans la librairie que j'utilise, la seule façon serait de créer le document Json à la main pour les requêtes de création, ce qui n'est pas franchement très propre.

Aurais-tu une autre solution à me proposer ?

**Comment by gaetanm** [comment]
Perso en regardant les commits je vois pas ce qui a pu changer ce comportement.

**Comment by AntoineDewaele** [comment]
C'est normal que l'id n'est pas accepté, il n'a rien à faire dans une requête comme celle la.
Quel est la lib que tu utilise ?

**Comment by Miyabimaru** [comment]
Je le sais bien mais je n'ai pas trouvé la possibilité de l'enlever. Pourtant dans les exemples de la lib à un moment il y a pas l'id mais j'ai beau faire exactement pareil l'id apparaît toujours dans ma requête quoi que je fasse.
Si jamais tu as le temps tu peux essayer de regarder, j'utilise cette lib :
https://github.com/scott-mcdonald/JsonApiFramework

**Comment by AntoineDewaele** [comment]
Oui c'est étrange, selon l'exemple de POST, la requête généré ne contient pas d'id..
Essaie de voir s'il n'y a pas un truc que tu fait mal (genre laisser un setID() quelque part ou alors avoir une config qui setID par defaut)

Moi de mon coté, c'est impossible d'accepter un id sur le POST c'est anti JSON:API et c'est même pas envisageable avec ma gem.
