### ISSUE TITLE
Surcharger les retours erreur 400, 404 et 500

### ISSUE THREAD

**Issue by AntoineDewaele** [DoEat/api.doeat#2]
- [ ] Créer un middleware à inserer avant ActionDispatch::ParamsParser pour surcharger l'erreur 400 bad request.
- [ ] Créer une route vers ErrorsController#eception pour surcharger le retour erreur 500
- [ ] Créer une route vers ErrorsController#not_found pour surcharger le retour erreur 404

Afin d'éviter les responses comme ça : 

![capture d ecran de 2016-10-22 22-12-39](https://cloud.githubusercontent.com/assets/9131295/19622202/b0dec9d6-98a4-11e6-8dfb-57b7d11c6cae.png)

**Comment by gaetanm** [comment]
Je pense pas qu'on ait besoin de passer par un middleware juste pour ça. D'ailleurs, il me semble qu'on a la stack d'erreur car on est en mode développement. En mode production, la stack apparait seulement dans les logs.

**Comment by AntoineDewaele** [comment]
C'est exact.
