### ISSUE TITLE
Recette n'apparaît pas après création

### ISSUE THREAD

**Issue by Miyabimaru** [DoEat/api.doeat#8]
Suite à la création réussie d'une recette (Code réponse 201 "created", etc), celle-ci n'apparaît pas après un GET de toutes les recettes.
Cependant, elle apparaît après un GET des recettes créées par l'utilisateur.

**Comment by AntoineDewaele** [comment]
C'est normal, les réponses sont paginées, si rien n'est précisé, l'api renvoit une page de 8 réponses.
http://jsonapi.org/format/#fetching-pagination

**Comment by Miyabimaru** [comment]
Merci, la pagination a été mise en place dans mon application, tout est réglé !
