### ISSUE TITLE
Error 500 : DELETE d'une recette

### ISSUE THREAD

**Issue by Miyabimaru** [DoEat/api.doeat#9]
En essayant de DELETE une recette, ici sur la recette du Coq au vin :
`httpClient.DeleteAsync(https://staging-doeat.herokuapp.com/api/v1/recipes/6);`
(`httpClient.DeleteAsync` qui est la fonction tout à fait basique de delete)
Le serveur me retourne :
```
StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Via: 1.1 vegur
  X-Request-Id: ce59536c-464a-477f-a723-01b52a964ca9
  Connection: keep-alive
  Server: Cowboy
  Transfer-Encoding: chunked
  Cache-Control: no-cache
  X-Runtime: 0.014369
  Date: Tue, 24 Jan 2017 16:13:39 GMT
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  X-Xss-Protection: 1; mode=block
  Content-Type: application/vnd.api+json; charset=utf-8
}
```

**Comment by AntoineDewaele** [comment]
Oui c'est normal. Je tacheterais de régler ce problème au plus vite.

**Comment by gaetanm** [comment]
Vu que la spec passe, j'imagine que le souci est lié à Heroku ?

**Comment by AntoineDewaele** [comment]
Non, la suppression n'est pas faite en cascade, du coup vu que Recipe est lié à Menu, il ne se supprime pas.
Mais je ne compte pas supprimer les recettes, juste leur mettre un boolean (active or not) pour que les utilisateurs ayant générer un menu avec cette recette puisse continuer à voir la recette. Elle sera juste innaccessible via recherche ou nouvelle génération de menu.

**Comment by AntoineDewaele** [comment]
La suppression des recettes fonctionne désormais.
La recette est juste 'disable' le temps que tous les menus générés qui la contienne expirent
